//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System;
using System.Collections.Generic;


namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Credenziali
    {
        public int UserID { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "Inserire username corretto")]
        public string username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Inserire password corretta")]
        public string password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
