//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatGen
    {
        public byte IDDatGen { get; set; }
        public string NomeProc { get; set; }
        public string Nome { get; set; }
        public string Indirizzo { get; set; }
        public string Città { get; set; }
        public string CAP { get; set; }
        public string Prov { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string IntLong { get; set; }
        public string IntShort { get; set; }
        public Nullable<short> Rec { get; set; }
        public string Deffuori { get; set; }
        public string Versione { get; set; }
        public string Wesite { get; set; }
    }
}
