//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLoc
    {
        public byte IDDatLoc { get; set; }
        public string Person { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Logon { get; set; }
        public Nullable<double> FirstTime { get; set; }
        public Nullable<byte> Level { get; set; }
        public string PathDati { get; set; }
        public string Stampante { get; set; }
    }
}
