//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtri_Parametri
    {
        public int IDFiltro { get; set; }
        public int IDP { get; set; }
        public string Prompt { get; set; }
        public int Ordine { get; set; }
        public string Valore { get; set; }
    
        public virtual Filtri Filtri { get; set; }
        public virtual TabParametriFiltri TabParametriFiltri { get; set; }
    }
}
