//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mem()
        {
            this.Pag = new HashSet<Pag>();
        }
    
        public int Cod { get; set; }
        public string Sesso { get; set; }
        public string Nom { get; set; }
        public string Titolo { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Ist { get; set; }
        public string Via { get; set; }
        public string CAP { get; set; }
        public string Cit { get; set; }
        public string Naz { get; set; }
        public Nullable<System.DateTime> DaNa { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> DimAn { get; set; }
        public Nullable<bool> NoStampa { get; set; }
        public Nullable<System.DateTime> Modificato { get; set; }
        public Nullable<int> PresentatoDa { get; set; }
        public Nullable<bool> FlagRegalo { get; set; }
        public Nullable<int> PresentatoDa2 { get; set; }
        public Nullable<bool> FlagRegalo2 { get; set; }
        public Nullable<short> AnnoPresentazione { get; set; }
        public string CodTitStu { get; set; }
    
        public virtual TabNaz TabNaz { get; set; }
        public virtual TabSex TabSex { get; set; }
        public virtual TabTitStu TabTitStu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pag> Pag { get; set; }
    }
}
