//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posta_Prototipi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posta_Prototipi()
        {
            this.Posta_Messaggi = new HashSet<Posta_Messaggi>();
        }
    
        public int Codice { get; set; }
        public string CodiceConn { get; set; }
        public string Sender { get; set; }
        public string NotificationTo { get; set; }
        public string ReceiptTo { get; set; }
        public string Subject { get; set; }
        public string Header { get; set; }
        public string Message { get; set; }
        public string Footer { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string emailtest { get; set; }
        public string Allegati { get; set; }
        public string Azione { get; set; }
        public string FullMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posta_Messaggi> Posta_Messaggi { get; set; }
        public virtual TabPosta TabPosta { get; set; }
    }
}
