//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Mem
    {
        public int Cod { get; set; }
        public string Sesso { get; set; }
        public string DescrSex { get; set; }
        public string Nom { get; set; }
        public string Titolo { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Ist { get; set; }
        public string Via { get; set; }
        public string CAP { get; set; }
        public string Cit { get; set; }
        public string Naz { get; set; }
        public string DescrNaz { get; set; }
        public Nullable<System.DateTime> DaNa { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> DimAn { get; set; }
        public Nullable<bool> NoStampa { get; set; }
        public Nullable<System.DateTime> Modificato { get; set; }
        public Nullable<int> PresentatoDa { get; set; }
        public string TitPres1 { get; set; }
        public string MomePres1 { get; set; }
        public string CognomePres1 { get; set; }
        public Nullable<bool> FlagRegalo { get; set; }
        public Nullable<int> PresentatoDa2 { get; set; }
        public string TitiPres2 { get; set; }
        public string NomePres2 { get; set; }
        public string CognomePres2 { get; set; }
        public Nullable<bool> FlagRegalo2 { get; set; }
        public Nullable<short> AnnoPresentazione { get; set; }
        public string CodTitStu { get; set; }
        public string DescrTitStu { get; set; }
    }
}
