//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Pag_Mem_Divisioni
    {
        public string CodDiv { get; set; }
        public Nullable<bool> Effettiva { get; set; }
        public string DescrDiv { get; set; }
        public Nullable<decimal> ImportoDiv { get; set; }
        public int CodP { get; set; }
        public short AnnoP { get; set; }
        public string Tiscr { get; set; }
        public string DescrTIscr { get; set; }
        public string Cat { get; set; }
        public string DescrCat { get; set; }
        public Nullable<decimal> Pagato { get; set; }
        public Nullable<decimal> Dovuto { get; set; }
        public Nullable<System.DateTime> DatPag { get; set; }
        public Nullable<System.DateTime> DatReg { get; set; }
        public Nullable<System.DateTime> DatCassa { get; set; }
        public string Tpag { get; set; }
        public string DescrTPag { get; set; }
        public string Fuori { get; set; }
        public Nullable<bool> Lode { get; set; }
        public string Carica { get; set; }
        public string DescrCarica { get; set; }
        public string Sez { get; set; }
        public string NCodSez { get; set; }
        public string Sett { get; set; }
        public string DescrSet { get; set; }
        public string Pos { get; set; }
        public string DescrPos { get; set; }
        public string Ent { get; set; }
        public string DescrEnt { get; set; }
        public int Cod { get; set; }
        public string Sesso { get; set; }
        public string DescrSex { get; set; }
        public string Nom { get; set; }
        public string Titolo { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Ist { get; set; }
        public string Via { get; set; }
        public string CAP { get; set; }
        public string Cit { get; set; }
        public string Naz { get; set; }
        public string DescrNaz { get; set; }
        public Nullable<System.DateTime> DaNa { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> DimAn { get; set; }
        public Nullable<bool> NoStampa { get; set; }
        public Nullable<System.DateTime> Modificato { get; set; }
        public Nullable<int> PresentatoDa { get; set; }
        public string TitPres1 { get; set; }
        public string MomePres1 { get; set; }
        public string CognomePres1 { get; set; }
        public Nullable<bool> FlagRegalo { get; set; }
        public Nullable<int> PresentatoDa2 { get; set; }
        public string TitiPres2 { get; set; }
        public string NomePres2 { get; set; }
        public string CognomePres2 { get; set; }
        public Nullable<bool> FlagRegalo2 { get; set; }
        public Nullable<short> AnnoPresentazione { get; set; }
        public string CodTitStu { get; set; }
        public string DescrTitStu { get; set; }
    }
}
