//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Pag
    {
        public int CodP { get; set; }
        public short AnnoP { get; set; }
        public string Tiscr { get; set; }
        public string DescrTIscr { get; set; }
        public string Cat { get; set; }
        public string DescrCat { get; set; }
        public Nullable<decimal> Pagato { get; set; }
        public Nullable<decimal> Dovuto { get; set; }
        public Nullable<System.DateTime> DatPag { get; set; }
        public Nullable<System.DateTime> DatReg { get; set; }
        public Nullable<System.DateTime> DatCassa { get; set; }
        public string Tpag { get; set; }
        public string DescrTPag { get; set; }
        public string Fuori { get; set; }
        public Nullable<bool> Lode { get; set; }
        public string Carica { get; set; }
        public string DescrCarica { get; set; }
        public string Sez { get; set; }
        public string NCodSez { get; set; }
        public string Sett { get; set; }
        public string DescrSet { get; set; }
        public string Pos { get; set; }
        public string DescrPos { get; set; }
        public string Ent { get; set; }
        public string DescrEnt { get; set; }
    }
}
