//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sci_newEntities : DbContext
    {
        public sci_newEntities()
            : base("name=sci_newEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Convenzioni> Convenzioni { get; set; }
        public virtual DbSet<DatGen> DatGen { get; set; }
        public virtual DbSet<DatLoc> DatLoc { get; set; }
        public virtual DbSet<Divisioni> Divisioni { get; set; }
        public virtual DbSet<Gruppi> Gruppi { get; set; }
        public virtual DbSet<Mem> Mem { get; set; }
        public virtual DbSet<Ordinamenti> Ordinamenti { get; set; }
        public virtual DbSet<Pag> Pag { get; set; }
        public virtual DbSet<Filtri> Filtri { get; set; }
        public virtual DbSet<Filtri_Parametri> Filtri_Parametri{ get; set; }
        public virtual DbSet<Riviste> Riviste { get; set; }
        public virtual DbSet<Stampe> Stampe { get; set; }
        public virtual DbSet<Storico> Storico { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TabCarica> TabCarica { get; set; }
        public virtual DbSet<TabCat> TabCat { get; set; }
        public virtual DbSet<TabConv> TabConv { get; set; }
        public virtual DbSet<TabDiv> TabDiv { get; set; }
        public virtual DbSet<TabEnt> TabEnt { get; set; }
        public virtual DbSet<TabGru> TabGru { get; set; }
        public virtual DbSet<TabNaz> TabNaz { get; set; }
        public virtual DbSet<TabPos> TabPos { get; set; }
        public virtual DbSet<TabParametriFiltri> TabParametriFiltri { get; set; }
        public virtual DbSet<TabPosta> TabPosta { get; set; }
        public virtual DbSet<Posta_Messaggi> Posta_Messaggi { get; set; }
        public virtual DbSet<Posta_Prototipi> Posta_Prototipi { get; set; }
        public virtual DbSet<TabRiv> TabRiv { get; set; }
        public virtual DbSet<TabSet> TabSet { get; set; }
        public virtual DbSet<TabSex> TabSex { get; set; }
        public virtual DbSet<TabSez> TabSez { get; set; }
        public virtual DbSet<TabTIscr> TabTIscr { get; set; }
        public virtual DbSet<TabTitStu> TabTitStu { get; set; }
        public virtual DbSet<TabTPag> TabTPag { get; set; }
        public virtual DbSet<TabValute> TabValute { get; set; }
        public virtual DbSet<Q_Mem> Q_Mem { get; set; }
        public virtual DbSet<Q_Pag> Q_Pag { get; set; }
        public virtual DbSet<Q_Pag_Mem> Q_Pag_Mem { get; set; }
        public virtual DbSet<Q_Pag_Mem_Convenzioni> Q_Pag_Mem_Convenzioni { get; set; }
        public virtual DbSet<Q_Pag_Mem_Divisioni> Q_Pag_Mem_Divisioni { get; set; }
        public virtual DbSet<Q_Pag_Mem_Gruppi> Q_Pag_Mem_Gruppi { get; set; }
        public virtual DbSet<Q_Pag_Mem_Riviste> Q_Pag_Mem_Riviste { get; set; }
    }
}
