//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stampe
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string NomeReport { get; set; }
        public string Descrizione { get; set; }
        public Nullable<int> IDFiltro { get; set; }
        public string Filtro { get; set; }
        public Nullable<int> IDOrdinamento { get; set; }
        public string Ordinamento { get; set; }
        public Nullable<bool> Filtrabile { get; set; }
        public Nullable<bool> Ordinabile { get; set; }
        public Nullable<bool> Selezionato { get; set; }
        public string QueryAmmesse { get; set; }
    
        public virtual Filtri Filtri { get; set; }
        public virtual Ordinamenti Ordinamenti { get; set; }
    }
}
