//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabDiv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabDiv()
        {
            this.Divisioni = new HashSet<Divisioni>();
        }
    
        public short AnnoDiv { get; set; }
        public string CodDiv { get; set; }
        public string NCodDiv { get; set; }
        public string DescrDiv { get; set; }
        public Nullable<decimal> ImportoDiv { get; set; }
        public Nullable<bool> SelDiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Divisioni> Divisioni { get; set; }
    }
}
