//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabPosta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabPosta()
        {
            this.Posta_Prototipi = new HashSet<Posta_Prototipi>();
        }
    
        public string Codice { get; set; }
        public string Descrizione { get; set; }
        public string smtpServer { get; set; }
        public Nullable<int> smtpServerPort { get; set; }
        public Nullable<byte> sendUsing { get; set; }
        public Nullable<byte> AutenticationType { get; set; }
        public string SendUsername { get; set; }
        public string SendPassword { get; set; }
        public string Sender { get; set; }
        public string NotificationTo { get; set; }
        public string ReceiptTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posta_Prototipi> Posta_Prototipi { get; set; }
    }
}
