//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRiv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabRiv()
        {
            this.Riviste = new HashSet<Riviste>();
        }
    
        public short AnnoRiv { get; set; }
        public string CodRiv { get; set; }
        public string NCodRiv { get; set; }
        public string DescrRiv { get; set; }
        public string DescrS { get; set; }
        public Nullable<decimal> ImportoRiv { get; set; }
        public string FormatoRiv { get; set; }
        public Nullable<byte> TipoRiv { get; set; }
        public Nullable<bool> SelRiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Riviste> Riviste { get; set; }
    }
}
