//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabValute
    {
        public short AnnoV { get; set; }
        public string FormatoV { get; set; }
        public Nullable<byte> DecimaliV { get; set; }
        public string Simbolo { get; set; }
    }
}
